[package]
name = "wasm-host"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmi = "0.31"
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json", "native-tls", "default-tls"] }
anyhow = "1.0"
futures = "0.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
urlencoding = "2.1.3"
thiserror = "2.0.12"
